project_id = "pykyijuvjzvktdywgszw"

[functions.send-apifon-sms]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = false

[functions.send-appointment-email]
verify_jwt = false